### PR TITLE
Renamed package and removed B-B-W directory

### PR DESCRIPTION
**Pull request by humanjas**
#158 

# Introduction
Cleaned the project directory by removing the B-B-W folder and renaming the package.

# Purpose
Cleaning the files that are not used and/ or do not follow the guidelines of naming packages.

# Details
none

# Future Applicability
The new package name is nl.tudelft.bbw.*

### CODE REVIEW

**Comment by humanjas** [comment]
Pulled from the feature/travisTimeoutFix into this branch to increase the chance that the travis build succeeds.

**Comment by ashay123** [comment]
Just renaming things, when the build succeeds this can be merged.

**Comment by ymte** [comment]
A lot of merge problems will be avoided when performing this merge later as a lot of classes inside Luat's, Ashay's, and my own PRs are still inside the old b_b_w package giving a lot of missing import errors.

**Comment by humanjas** [comment]
When you merge this pr, you can easily merge it, by rightclicking on your package and press rename package.

**Comment by ymte** [comment]
True, but then these refactoring changes will be included in my own branch while it should be done in this branch

**Comment by humanjas** [comment]
When this pr gets merged, the new classes should be in the bbw package as well. It is just that you have to make sure that your new classes are in the new package, and this is making sure that your branch is able to merge with the new develop branch. So of course this is addressed in your pr as well, but that does not mean the issue cannot be addressed earlier.

**Comment by ymte** [comment]
The moving of my classes to the new package is not my responsibility and should happen in this pull request.

**Comment by humanjas** [comment]
However, making sure that your pr is able to merge with the new develop branch is.

**Pull request merged**
