### PR TITLE
Moved entire project to root of github folder

### PR DESCRIPTION
**Pull request by ymte**
# Purpose
This pull request is made to facilitate easier execution of the travis ci engine. The project folder was located inside (home)/B-B-W/, which only left two files in our real (home). This added visual noide and complexity to the project, and was easy to fix by moving all source files.

# Remarks
Since a new project had to be created anyway, the app now targets a minimum sdk version of Android 4.0.3 (IceCreamSandwich), which makes it run on around 97.3% of devices  occurring in the wild.

### CODE REVIEW

**Comment by humanjas** [comment]
The builds are failing, so if you can have a look at it.

The rest looks fine.

**Comment by ymte** [comment]
# Addendum
Packages are renamed with lower case, activities are moved to the view package.

**Comment by ashay123** [comment]
As @humanjas already said, the builds are failing. However, I think this pull request is a great step towards a passing build, because the project structure now is more clear and manageable,

**Comment by deepweeb** [comment]
Yes for now just pull it, so we can further advance and then fix the build.

**Comment by nzarin** [comment]
I agree with the rest of the group except for Luat. he is chineese

**Comment by nzarin** [comment]
I agree with the rest of the group.

**Comment by ymte** [comment]
# Travis CI will not work anytime soon. It does not work at all so I will need more time to sort it out.

**Pull request closed without merging**
