### PR TITLE
Weekly Merge Develop to Master

### PR DESCRIPTION
**Pull request by ghost**
# Introduction
The final weekly merge from develop to master.

# Purpose
To bring the master up to date.

# Details
We want to merge the develop to master.

# Future Applicability
None

### CODE REVIEW

**Review by tjappo — APPROVED** [review]
Looks good, already placed comments on the previous PRs

**Review by ashay123 — APPROVED** [review]

**Review by deepweeb — APPROVED** [review]
Nice diff from everyone.

**Review by nzarin — APPROVED** [review]
Despite of all the issues we had, all the difficulties we had to overcome, we can finally say: We made it. This product meets the requirements. Although we have some problems (building, see EAD why this is still a problem), we can release this with a positive feeling.

**Pull request merged**
